// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForCreatePlayers implements pgx.CopyFromSource.
type iteratorForCreatePlayers struct {
	rows                 []CreatePlayersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePlayers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePlayers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FirstName,
		r.rows[0].LastName,
		r.rows[0].Name,
		r.rows[0].Division,
	}, nil
}

func (r iteratorForCreatePlayers) Err() error {
	return nil
}

func (q *Queries) CreatePlayers(ctx context.Context, arg []CreatePlayersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"players"}, []string{"first_name", "last_name", "name", "division"}, &iteratorForCreatePlayers{rows: arg})
}
