// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: players.sql

package repository

import (
	"context"
)

type CreatePlayersParams struct {
	FirstName string
	LastName  string
	Name      string
	Division  string
}

const getPlayers = `-- name: GetPlayers :many
select id, name, first_name, last_name, division from players
order by first_name
`

func (q *Queries) GetPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, getPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FirstName,
			&i.LastName,
			&i.Division,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
